
import type { Metadata } from 'next'
import LeftSideBar from '@/components/home-route/left-sidebar/left-sidebar-container'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function HomeLayout({
  children,details,serieslist
}: {
  children: React.ReactNode,
  details:React.ReactNode,
  serieslist:React.ReactNode,
}) {
  
  return (

        <main className='flex w-full   '>
       
        <section className=" flex w-full  ">
        <div>{serieslist}</div>
        {children}
        <div className='w-full  overflow-hidden'>{details}</div>
        </section>
        
        
      
       </main>
       
  )
}
