import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LeftSideBar from "@/components/home-route/left-sidebar/left-sidebar-container";
import BackForth from "@/components/back-forth";
import Details from "@/components/dd";
const inter = Poppins({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  details,
  serieslist,
}: {
  children: React.ReactNode;
  details: React.ReactNode;
  serieslist: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full">
          <section className=" flex w-full ">
            <div className=" border-gray-600 w-40 h-screen">
              <LeftSideBar />
            </div>
            <BackForth />
            <Details>
              <div className="flex w-full flex-row">
                <div className=" w-screen sm:w-1/3  h-screen pr-20 pl-2 sm:pr-4">
                  {serieslist}
                </div>
                <div className="w-screen sm:w-80  h-screen ">{details}</div>
              </div>
            </Details>
          </section>
        </div>
      </body>
    </html>
  );
}
